#' Create HyperMS2 from mapped and unmapped MS2s
#'
#' This function is used to merge mapped and unmapped MS2s.
#'
#'
#' @param mapped_msms A MS2 list generated by \code{\link{map_features}}
#' @param centroid If each individual ion should be centroided first. Default TRUE
#' @param merge If set to TRUE, MS2s will be merge to HyperMS2. Default TRUE
#' @param centroid_after_merge If set to TRUE, a centroiding will be done on each HyperMS2.
#' @param ppm ppm tolerance for matching MS2s. Default 10
#' @param ppm_precursor ppm tolerance for matching precursors only for unmapped MS2s. Default 10
#' @param abs_mz Absolute tolerance for matching MS2s. Default 0.01
#' @param abs_mz_precursor Absolute tolerance for matching precursors only for unmapped MS2s. Default 0.01
#' @param rt Retention time tolerance for matching precursors only for unmapped MS2s (seconds). Default 10
#' @param centroid_onlymapped Set to TRUE to performed centroiding only for mapped MS2s. Default TRUE
#' @param merge_onlymapped Set to TRUE to performed merging only for mapped MS2s. Default FALSE
#' @param int_threshold The absolute intensity threshold for removing MS2 signals. Default 0
#' @param verbose Show information about different stages of the processes. Default FALSE
#' @export
#' @examples
#'
#' library(CAMERA)
#' library(metaboraid)
#' # Read MS1 and MS2 files
#' ms1_files<-system.file("ms1data",c("X1_Rep1.mzML","X2_Rep1.mzML"),package = "metaboraid")
#' ms2_files<-system.file("ms2data",c("sample1.mzML","sample2.mzML"),package = "metaboraid")
#'
#' # mass trace detection
#' xs <- xcmsSet(ms1_files,method="centWave",ppm=30,peakwidth=c(5,10))
#'
#' # mass trace matching
#' xsg <- group(xs)
#'
#' # convert to CAMERA
#' xsa <- xsAnnotate(xsg)
#'
#' # Group mass traces
#' anF <- groupFWHM(xsa, perfwhm = 0.6)
#'
#' # Detect isotopes
#' anI <- findIsotopes(anF, mzabs = 0.01)
#'
#' # Group using correlation
#' anIC <- groupCorr(anI, cor_eic_th = 0.75)
#'
#' # Find adducts
#' anFA <- findAdducts(anIC, polarity="positive")
#'
#' # map features and MS2s
#' mapped_features<-map_features(inputMS2s = ms2_files,input_camera = anFA,ppm = 10,rt = 10)
#' preprocess_msms(mapped_features)
#'
#'
#' @return
#' A similar format as input but the MS2s has been pre-processed: A list with two elements, mapped and unmapped.
#'
#' @details
#' Often multiple ions are picked by mass spectrometer are originated from the same precursor.
#' This function attempts to combine the ions originating from the same precursor.
#' For mapped ions, we merge the MS2s that have been mapped to the same feature.
#' For unmapped ions, we do a clustering using RT and ppm tolerance (on precursor) we then perform the merging.
#'
#' @import reticulate
#' @import zip
#' @import parallel
#' @import future
#' @import progressr
#' @import future.apply
#' @import plyr
#' @import xcms
#' @MSnbase


preprocess_msms<-function(mapped_msms=NA,centroid=F,merge=TRUE,centroid_after_merge=F,ppm=10,ppm_precursor=10,abs_mz=0.01,abs_mz_precursor=0.01,rt=10,centroid_onlymapped=FALSE,merge_onlymapped=FALSE,int_threshold=0,verbose=FALSE)
{
  if(!is.logical(verbose)){
    stop("verbose must be TRUE or FALSE!")
  }

  if(verbose)cat("Checking inputs ...","\n")
  if(!is.list(mapped_msms))
  {
    stop("mapped_msms has to be a list from map_features")
  }else{
    if(!all(names(mapped_msms)==c("mapped","unmapped"))){
      stop("mapped_msms does not appear to be map_features! mapped_msms has to be a list from map_features!")
    }
    if(all(sapply(mapped_msms, length)<1)){
      stop("No MS2s were found in mapped_msms")
    }
  }

  if(!is.logical(centroid)){
    stop("centroid must be TRUE or FALSE!")
  }

  if(!is.logical(merge)){
    stop("merge must be TRUE or FALSE!")
  }

  if(!is.logical(centroid_after_merge)){
    stop("centroid_after_merge must be TRUE or FALSE!")
  }

  if(!is.logical(merge_onlymapped)){
    stop("merge_onlymapped must be TRUE or FALSE!")
  }

  if(!is.logical(centroid_onlymapped)){
    stop("centroid_onlymapped must be TRUE or FALSE!")
  }



  if(any(is.na(ppm)) | any(is.null(ppm)))
  {
    stop("No ppm input have been provided!")
  }

  if(!is.numeric(rt))
  {
    stop("rt must be numberic")
  }

  if(!is.numeric(int_threshold))
  {
    stop("int_threshold must be numberic")
  }


  if(!is.numeric(ppm_precursor))
  {
    stop("ppm_precursor must be numberic")
  }

  if(!is.numeric(abs_mz_precursor))
  {
    stop("abs_mz_precursor must be numberic")
  }

  if(abs_mz_precursor<0)
  {
    stop("abs_mz_precursor must be numberic and higher than 0")
  }



  if(!is.numeric(abs_mz))
  {
    stop("abs_mz must be numberic")
  }


  if(!is.numeric(ppm))
  {
    stop("ppm must be numberic")
  }

  if(ppm<0)
  {
    stop("ppm must be numberic and higher than 0")
  }

  if(rt<0)
  {
    stop("rt must be numberic and higher than 0")
  }

  if(abs_mz<0)
  {
    stop("abs_mz must be numberic and higher than 0")
  }
  if(ppm_precursor<0)
  {
    stop("ppm_precursor must be numberic and higher than 0")
  }



  if(centroid==TRUE){
    if(verbose)cat("Centroiding ...","\n")
    for(i in 1:length(mapped_msms$mapped))
    {
      for(j in 1:length(mapped_msms$mapped[[i]]))
      {
        MSMS<-mapped_msms$mapped[[i]][[j]]
        MSMS@centroided<-F
        MSMS@polarity<-as.integer(1)
        MSMS@smoothed<-F
        MSMS<-MSnbase::pickPeaks(MSMS)
        mapped_msms$mapped[[i]][[j]]<-MSMS
      }
    }

    if(!centroid_onlymapped){
      for(i in 1:length(mapped_msms$unmapped))
      {

          MSMS<-mapped_msms$unmapped[[i]]
          MSMS@centroided<-F
          MSMS@polarity<-as.integer(1)
          MSMS@smoothed<-F
          MSMS<-MSnbase::pickPeaks(MSMS)
          mapped_msms$unmapped[[i]]<-MSMS

      }
    }
  }

  if(merge==TRUE)
  {
    if(verbose)cat("Creating hyperMS2 for mapped ions...","\n")
    for(i in 1:length(mapped_msms$mapped))
    {
      if(length(mapped_msms$mapped[[i]])>1)
      {
        merge_msms<-merge.spectra.group(mapped_msms$mapped[[i]],eppm = ppm* 10e-6,eabs = abs_mz_precursor,int.threshold = int_threshold)
        if(centroid_after_merge==TRUE)
        {
          MSMS<-merge_msms
          MSMS@centroided<-F
          MSMS@polarity<-as.integer(1)
          MSMS@smoothed<-F
          MSMS<-MSnbase::pickPeaks(MSMS)
          merge_msms<-MSMS
        }
        mapped_msms$mapped[[i]]<-list(merge_msms)
      }
    }

    if(merge_onlymapped==FALSE)
    {
      a <- collect.spectra.lists(mapped_msms$unmapped, abs_mz, ppm_precursor, rt)
      merged.spectra <- sapply(1:length(a), function(x) {
        merge.spectra.group(a[[x]], ppm * 10e-6, abs_mz, int_threshold)
      })

      if(centroid_onlymapped==FALSE & centroid_after_merge==TRUE)
      {
        list_of_unmapped<-c()
        for(i in 1:length(merged.spectra))
        {

          MSMS<-merged.spectra[[i]]
          MSMS@centroided<-F
          MSMS@polarity<-as.integer(1)
          MSMS@smoothed<-F
          MSMS<-MSnbase::pickPeaks(MSMS)
          list_of_unmapped[[i]]<-MSMS

        }
        mapped_msms$unmapped<-list_of_unmapped
      }

    }


  }

  return(mapped_msms)


}
